language: node_js
node_js:
  - v7.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm run lint && npm test -- --coverage
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CXX=g++-4.8
